;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/weather]
type = custom/script
; Command to be executed
exec = ~/.config/polybar/forest/scripts/weather.sh
; Seconds to sleep between updates
interval = 1800
click-left = ~/.config/polybar/forest/scripts/weather.sh refresh &
format = <label>
format-foreground = ${color.foreground}
label = " %output%"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
